# Generated by Django 5.0.1 on 2024-01-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
